// Code generated by go-swagger; DO NOT EDIT.

// Package restapi User Management API
//
//	API to manage users into a database with CRUD operations
//	Schemes:
//	  http
//	Host: localhost:8082
//	BasePath: /
//	Version: 1.0.0
//
//	Consumes:
//	  - application/json
//
//	Produces:
//	  - application/json
//
// swagger:meta
package restapi
