// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PostUsersCreatedCode is the HTTP code returned for type PostUsersCreated
const PostUsersCreatedCode int = 201

/*
PostUsersCreated User added successfully

swagger:response postUsersCreated
*/
type PostUsersCreated struct {
}

// NewPostUsersCreated creates PostUsersCreated with default headers values
func NewPostUsersCreated() *PostUsersCreated {

	return &PostUsersCreated{}
}

// WriteResponse to the client
func (o *PostUsersCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(201)
}

// PostUsersBadRequestCode is the HTTP code returned for type PostUsersBadRequest
const PostUsersBadRequestCode int = 400

/*
PostUsersBadRequest Invalid requesta

swagger:response postUsersBadRequest
*/
type PostUsersBadRequest struct {
}

// NewPostUsersBadRequest creates PostUsersBadRequest with default headers values
func NewPostUsersBadRequest() *PostUsersBadRequest {

	return &PostUsersBadRequest{}
}

// WriteResponse to the client
func (o *PostUsersBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// PostUsersInternalServerErrorCode is the HTTP code returned for type PostUsersInternalServerError
const PostUsersInternalServerErrorCode int = 500

/*
PostUsersInternalServerError Internal error server

swagger:response postUsersInternalServerError
*/
type PostUsersInternalServerError struct {
}

// NewPostUsersInternalServerError creates PostUsersInternalServerError with default headers values
func NewPostUsersInternalServerError() *PostUsersInternalServerError {

	return &PostUsersInternalServerError{}
}

// WriteResponse to the client
func (o *PostUsersInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
