// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PutUsersIDOKCode is the HTTP code returned for type PutUsersIDOK
const PutUsersIDOKCode int = 200

/*
PutUsersIDOK User updated successfully

swagger:response putUsersIdOK
*/
type PutUsersIDOK struct {
}

// NewPutUsersIDOK creates PutUsersIDOK with default headers values
func NewPutUsersIDOK() *PutUsersIDOK {

	return &PutUsersIDOK{}
}

// WriteResponse to the client
func (o *PutUsersIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// PutUsersIDBadRequestCode is the HTTP code returned for type PutUsersIDBadRequest
const PutUsersIDBadRequestCode int = 400

/*
PutUsersIDBadRequest Invalid request

swagger:response putUsersIdBadRequest
*/
type PutUsersIDBadRequest struct {
}

// NewPutUsersIDBadRequest creates PutUsersIDBadRequest with default headers values
func NewPutUsersIDBadRequest() *PutUsersIDBadRequest {

	return &PutUsersIDBadRequest{}
}

// WriteResponse to the client
func (o *PutUsersIDBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// PutUsersIDInternalServerErrorCode is the HTTP code returned for type PutUsersIDInternalServerError
const PutUsersIDInternalServerErrorCode int = 500

/*
PutUsersIDInternalServerError Internal error server

swagger:response putUsersIdInternalServerError
*/
type PutUsersIDInternalServerError struct {
}

// NewPutUsersIDInternalServerError creates PutUsersIDInternalServerError with default headers values
func NewPutUsersIDInternalServerError() *PutUsersIDInternalServerError {

	return &PutUsersIDInternalServerError{}
}

// WriteResponse to the client
func (o *PutUsersIDInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
