// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DeleteUsersIDOKCode is the HTTP code returned for type DeleteUsersIDOK
const DeleteUsersIDOKCode int = 200

/*
DeleteUsersIDOK Usuario eliminado exitosamente

swagger:response deleteUsersIdOK
*/
type DeleteUsersIDOK struct {
}

// NewDeleteUsersIDOK creates DeleteUsersIDOK with default headers values
func NewDeleteUsersIDOK() *DeleteUsersIDOK {

	return &DeleteUsersIDOK{}
}

// WriteResponse to the client
func (o *DeleteUsersIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// DeleteUsersIDBadRequestCode is the HTTP code returned for type DeleteUsersIDBadRequest
const DeleteUsersIDBadRequestCode int = 400

/*
DeleteUsersIDBadRequest Solicitud inválida

swagger:response deleteUsersIdBadRequest
*/
type DeleteUsersIDBadRequest struct {
}

// NewDeleteUsersIDBadRequest creates DeleteUsersIDBadRequest with default headers values
func NewDeleteUsersIDBadRequest() *DeleteUsersIDBadRequest {

	return &DeleteUsersIDBadRequest{}
}

// WriteResponse to the client
func (o *DeleteUsersIDBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// DeleteUsersIDInternalServerErrorCode is the HTTP code returned for type DeleteUsersIDInternalServerError
const DeleteUsersIDInternalServerErrorCode int = 500

/*
DeleteUsersIDInternalServerError Error interno del servidor

swagger:response deleteUsersIdInternalServerError
*/
type DeleteUsersIDInternalServerError struct {
}

// NewDeleteUsersIDInternalServerError creates DeleteUsersIDInternalServerError with default headers values
func NewDeleteUsersIDInternalServerError() *DeleteUsersIDInternalServerError {

	return &DeleteUsersIDInternalServerError{}
}

// WriteResponse to the client
func (o *DeleteUsersIDInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
